name: juju
version: 2.0-beta13
summary: juju client
description: Through the use of charms, juju provides you with shareable, re-usable, and repeatable expressions of devops best practices.
confinement: devmode

apps:
  juju:
    command: bin/juju
    plugs: [network, network-bind, home]

parts:
  juju:
    plugin: godeps
    go-importpath: github.com/juju/juju
    source: https://github.com/juju/juju.git
    source-type: git
    source-tag: juju-2.0-beta13
